# Generated by Django 4.1 on 2022-10-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='unique_key',
            field=models.IntegerField(unique=True),
        ),
    ]
