# Generated by Django 4.1 on 2022-10-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0002_alter_crime_unique_key'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='crime',
            index_together={('primary_type', 'date')},
        ),
    ]
