version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1"
    ports:
      - 6432:5432
  redis:
    image: redis:6.0.3-alpine
    volumes:
      - redisdata:/data
    command: redis-server --bind 0.0.0.0
    ports:
      - 6379:6379
  crime-inspector:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  streamlit-dashboard:
    build:
      context: "./streamlit_dashboard"
      dockerfile: "Dockerfile"
    ports:
      - 8502:8501
    env_file:
      - ./streamlit_dashboard/.env

volumes:
  pgdata:
  redisdata: