PRIMARY_TYPES = ['CONCEALED CARRY LICENSE VIOLATION',
                 'DECEPTIVE PRACTICE', 'DOMESTIC VIOLENCE',
                 'NON - CRIMINAL',
                 'THEFT',
                 'OTHER NARCOTIC VIOLATION',
                 'ARSON',
                 'HOMICIDE',
                 'GAMBLING',
                 'BURGLARY',
                 'RITUALISM',
                 'INTIMIDATION',
                 'ROBBERY',
                 'PUBLIC PEACE VIOLATION',
                 'CRIMINAL DAMAGE',
                 'NON-CRIMINAL (SUBJECT SPECIFIED)',
                 'LIQUOR LAW VIOLATION',
                 'INTERFERENCE WITH PUBLIC OFFICER',
                 'OFFENSE INVOLVING CHILDREN',
                 'NON-CRIMINAL',
                 'PROSTITUTION',
                 'STALKING',
                 'ASSAULT',
                 'BATTERY',
                 'HUMAN TRAFFICKING',
                 'CRIM SEXUAL ASSAULT',
                 'CRIMINAL TRESPASS',
                 'OTHER OFFENSE',
                 'MOTOR VEHICLE THEFT',
                 'KIDNAPPING',
                 'OBSCENITY',
                 'SEX OFFENSE',
                 'CRIMINAL SEXUAL ASSAULT',
                 'PUBLIC INDECENCY',
                 'WEAPONS VIOLATION',
                 'NARCOTICS']
